// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Clear stale ES256 sessions from old Lovable project — new Supabase uses HS256
supabase.auth.getSession().then(({ data: { session } }) => {
  if (session?.access_token?.startsWith('eyJhbGciOiJFUzI1NiIs')) {
    console.warn('[Auth] Sessão ES256 detectada (Lovable antigo), forçando logout');
    supabase.auth.signOut();
  }
});