// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Verify stored session is still valid on the server — clear if rejected
supabase.auth.getSession().then(({ data: { session } }) => {
  if (!session) return;
  supabase.auth.getUser().then(({ error }) => {
    if (error) {
      console.warn('[Auth] Sessão local inválida no servidor, forçando logout:', error.message);
      supabase.auth.signOut();
    }
  });
});